#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

dir_viewpower="/opt/UPS"
RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

case "$1" in
    configure)
        # Activate package triggers
        dpkg-trigger update-workbench

# Initialize and migrate configuration database.
        echo "${GREEN}Updating configuration database ...${ENDCOLOR}"
        omv-confdbadm create "conf.service.viewpowerups"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.viewpowerups" "${2}"
        fi

        if [ -d "$dir_viewpower" ]
        then
            echo "${GREEN}ViewPower Is Installed${ENDCOLOR}"
        else
            echo "${RED}Install ViewPower Software${ENDCOLOR}"
            wget -O /tmp/ViewPower_linux_x64_text.tar.gz https://www.power-software-download.com/viewpower/ViewPower_linux_x64_text.tar.gz
            tar xzvf /tmp/ViewPower_linux_x64_text.tar.gz
            rm -fr /tmp/ViewPower_linux_x64_text.tar.gz
            chmod 755 /tmp/ViewPower_linux_x64_text.sh
            /bin/sh /tmp/ViewPower_linux_x64_text.sh
            ln -s /etc/init.d/upsMonitor /opt/UPS/upsMonitor
            echo "${RED}Installation Complet Continuate${ENDCOLOR}"
        fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
